# Generated by Django 2.1.2 on 2018-10-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_Bidder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Auction_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.IntegerField(db_index=True, unique=True)),
                ('scheduled_date', models.DateTimeField()),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('description', models.TextField()),
                ('item_name', models.CharField(max_length=20)),
                ('status', models.BinaryField(default=0)),
                ('base_price', models.FloatField()),
                ('updated_price', models.FloatField()),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auctions.Auction_Details')),
                ('bidder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auctions.Item_Details')),
            ],
        ),
        migrations.AddField(
            model_name='auction_bidder',
            name='auction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auctions.Auction_Details'),
        ),
        migrations.AddField(
            model_name='auction_bidder',
            name='bidder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Profile'),
        ),
    ]
