# Generated by Django 2.1.2 on 2018-11-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20181030_1932'),
        ('Auctions', '0002_auto_20181030_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('1', 'Electronics'), ('2', 'Automobiles'), ('3', 'Fashion'), ('4', 'Sports'), ('5', 'Art'), ('6', 'Books'), ('7', 'Furniture'), ('8', 'Antiques'), ('9', 'Musical Equipment'), ('10', 'Industrial Equipment'), ('11', 'Gaming'), ('12', 'Stationary'), ('13', 'Industrial Equipment'), ('14', 'Gaming'), ('15', 'Jewellery'), ('16', 'Miscellaneous')], max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('base_price', models.FloatField()),
                ('keywords', models.CharField(max_length=255)),
                ('status', models.BinaryField(default=False)),
                ('updated_price', models.FloatField(default=0)),
                ('bidder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemList', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Auctions.Auction')),
            ],
        ),
        migrations.RemoveField(
            model_name='auction_bidder',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='auction_bidder',
            name='bidder_id',
        ),
        migrations.RemoveField(
            model_name='auction_details',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='item_details',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='item_details',
            name='bidder_id',
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='item_id',
        ),
        migrations.DeleteModel(
            name='Auction_Bidder',
        ),
        migrations.DeleteModel(
            name='Auction_Details',
        ),
        migrations.DeleteModel(
            name='Item_Details',
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auctions.ItemSet'),
        ),
    ]
