# Generated by Django 2.1.2 on 2018-11-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20181030_1932'),
        ('Auctions', '0003_auto_20181102_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionBidders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auctions.Auction')),
                ('bidders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Profile')),
            ],
        ),
    ]
